// AUTO-GENERATED by scripts/generate-image-data.mjs — do not edit by hand.
// Regenerate with `npm run optimize-images`.
import type { ImageData } from '../components/SphereImageGrid';
import type { AlbumPhoto } from './albums';

// 23 homepage-sphere photos (square thumb + full).
export const homePhotos: ImageData[] = [
  {
    "id": "DSC03575",
    "src": "/photos/home/DSC03575-thumb.jpg",
    "full": "/photos/home/DSC03575-full.jpg",
    "alt": "Hiccupviews photography — DSC03575"
  },
  {
    "id": "DSC05702",
    "src": "/photos/home/DSC05702-thumb.jpg",
    "full": "/photos/home/DSC05702-full.jpg",
    "alt": "Hiccupviews photography — DSC05702"
  },
  {
    "id": "DSC05842-2",
    "src": "/photos/home/DSC05842-2-thumb.jpg",
    "full": "/photos/home/DSC05842-2-full.jpg",
    "alt": "Hiccupviews photography — DSC05842-2"
  },
  {
    "id": "DSC05951-2",
    "src": "/photos/home/DSC05951-2-thumb.jpg",
    "full": "/photos/home/DSC05951-2-full.jpg",
    "alt": "Hiccupviews photography — DSC05951-2"
  },
  {
    "id": "DSC06051-2",
    "src": "/photos/home/DSC06051-2-thumb.jpg",
    "full": "/photos/home/DSC06051-2-full.jpg",
    "alt": "Hiccupviews photography — DSC06051-2"
  },
  {
    "id": "KLR00148",
    "src": "/photos/home/KLR00148-thumb.jpg",
    "full": "/photos/home/KLR00148-full.jpg",
    "alt": "Hiccupviews photography — KLR00148"
  },
  {
    "id": "KLR00175",
    "src": "/photos/home/KLR00175-thumb.jpg",
    "full": "/photos/home/KLR00175-full.jpg",
    "alt": "Hiccupviews photography — KLR00175"
  },
  {
    "id": "KLR00562",
    "src": "/photos/home/KLR00562-thumb.jpg",
    "full": "/photos/home/KLR00562-full.jpg",
    "alt": "Hiccupviews photography — KLR00562"
  },
  {
    "id": "KLR01135",
    "src": "/photos/home/KLR01135-thumb.jpg",
    "full": "/photos/home/KLR01135-full.jpg",
    "alt": "Hiccupviews photography — KLR01135"
  },
  {
    "id": "KLR01235",
    "src": "/photos/home/KLR01235-thumb.jpg",
    "full": "/photos/home/KLR01235-full.jpg",
    "alt": "Hiccupviews photography — KLR01235"
  },
  {
    "id": "KLR01528",
    "src": "/photos/home/KLR01528-thumb.jpg",
    "full": "/photos/home/KLR01528-full.jpg",
    "alt": "Hiccupviews photography — KLR01528"
  },
  {
    "id": "KLR02013",
    "src": "/photos/home/KLR02013-thumb.jpg",
    "full": "/photos/home/KLR02013-full.jpg",
    "alt": "Hiccupviews photography — KLR02013"
  },
  {
    "id": "KLR02129",
    "src": "/photos/home/KLR02129-thumb.jpg",
    "full": "/photos/home/KLR02129-full.jpg",
    "alt": "Hiccupviews photography — KLR02129"
  },
  {
    "id": "KLR02172",
    "src": "/photos/home/KLR02172-thumb.jpg",
    "full": "/photos/home/KLR02172-full.jpg",
    "alt": "Hiccupviews photography — KLR02172"
  },
  {
    "id": "KLR03647",
    "src": "/photos/home/KLR03647-thumb.jpg",
    "full": "/photos/home/KLR03647-full.jpg",
    "alt": "Hiccupviews photography — KLR03647"
  },
  {
    "id": "KLR03810",
    "src": "/photos/home/KLR03810-thumb.jpg",
    "full": "/photos/home/KLR03810-full.jpg",
    "alt": "Hiccupviews photography — KLR03810"
  },
  {
    "id": "KLR04543",
    "src": "/photos/home/KLR04543-thumb.jpg",
    "full": "/photos/home/KLR04543-full.jpg",
    "alt": "Hiccupviews photography — KLR04543"
  },
  {
    "id": "KLR05737",
    "src": "/photos/home/KLR05737-thumb.jpg",
    "full": "/photos/home/KLR05737-full.jpg",
    "alt": "Hiccupviews photography — KLR05737"
  },
  {
    "id": "KLR06673",
    "src": "/photos/home/KLR06673-thumb.jpg",
    "full": "/photos/home/KLR06673-full.jpg",
    "alt": "Hiccupviews photography — KLR06673"
  },
  {
    "id": "KLR07205",
    "src": "/photos/home/KLR07205-thumb.jpg",
    "full": "/photos/home/KLR07205-full.jpg",
    "alt": "Hiccupviews photography — KLR07205"
  },
  {
    "id": "KLR08956",
    "src": "/photos/home/KLR08956-thumb.jpg",
    "full": "/photos/home/KLR08956-full.jpg",
    "alt": "Hiccupviews photography — KLR08956"
  },
  {
    "id": "KLR09564",
    "src": "/photos/home/KLR09564-thumb.jpg",
    "full": "/photos/home/KLR09564-full.jpg",
    "alt": "Hiccupviews photography — KLR09564"
  },
  {
    "id": "KLR09951",
    "src": "/photos/home/KLR09951-thumb.jpg",
    "full": "/photos/home/KLR09951-full.jpg",
    "alt": "Hiccupviews photography — KLR09951"
  }
];

// 21 portrait photos (grid + full).
export const portraitPhotos: AlbumPhoto[] = [
  {
    "src": "/photos/portraits/DSC05702-grid.jpg",
    "full": "/photos/portraits/DSC05702-full.jpg",
    "alt": "Hiccupviews portrait — DSC05702"
  },
  {
    "src": "/photos/portraits/KLR00148-grid.jpg",
    "full": "/photos/portraits/KLR00148-full.jpg",
    "alt": "Hiccupviews portrait — KLR00148"
  },
  {
    "src": "/photos/portraits/KLR00562-grid.jpg",
    "full": "/photos/portraits/KLR00562-full.jpg",
    "alt": "Hiccupviews portrait — KLR00562"
  },
  {
    "src": "/photos/portraits/KLR00563-grid.jpg",
    "full": "/photos/portraits/KLR00563-full.jpg",
    "alt": "Hiccupviews portrait — KLR00563"
  },
  {
    "src": "/photos/portraits/KLR00636-grid.jpg",
    "full": "/photos/portraits/KLR00636-full.jpg",
    "alt": "Hiccupviews portrait — KLR00636"
  },
  {
    "src": "/photos/portraits/KLR00664-grid.jpg",
    "full": "/photos/portraits/KLR00664-full.jpg",
    "alt": "Hiccupviews portrait — KLR00664"
  },
  {
    "src": "/photos/portraits/KLR01083-grid.jpg",
    "full": "/photos/portraits/KLR01083-full.jpg",
    "alt": "Hiccupviews portrait — KLR01083"
  },
  {
    "src": "/photos/portraits/KLR01135-grid.jpg",
    "full": "/photos/portraits/KLR01135-full.jpg",
    "alt": "Hiccupviews portrait — KLR01135"
  },
  {
    "src": "/photos/portraits/KLR01528-grid.jpg",
    "full": "/photos/portraits/KLR01528-full.jpg",
    "alt": "Hiccupviews portrait — KLR01528"
  },
  {
    "src": "/photos/portraits/KLR01528-2-grid.jpg",
    "full": "/photos/portraits/KLR01528-2-full.jpg",
    "alt": "Hiccupviews portrait — KLR01528-2"
  },
  {
    "src": "/photos/portraits/KLR03810-grid.jpg",
    "full": "/photos/portraits/KLR03810-full.jpg",
    "alt": "Hiccupviews portrait — KLR03810"
  },
  {
    "src": "/photos/portraits/KLR04054-grid.jpg",
    "full": "/photos/portraits/KLR04054-full.jpg",
    "alt": "Hiccupviews portrait — KLR04054"
  },
  {
    "src": "/photos/portraits/KLR04543-grid.jpg",
    "full": "/photos/portraits/KLR04543-full.jpg",
    "alt": "Hiccupviews portrait — KLR04543"
  },
  {
    "src": "/photos/portraits/KLR05233-grid.jpg",
    "full": "/photos/portraits/KLR05233-full.jpg",
    "alt": "Hiccupviews portrait — KLR05233"
  },
  {
    "src": "/photos/portraits/KLR05737-grid.jpg",
    "full": "/photos/portraits/KLR05737-full.jpg",
    "alt": "Hiccupviews portrait — KLR05737"
  },
  {
    "src": "/photos/portraits/KLR08326-grid.jpg",
    "full": "/photos/portraits/KLR08326-full.jpg",
    "alt": "Hiccupviews portrait — KLR08326"
  },
  {
    "src": "/photos/portraits/KLR08932-grid.jpg",
    "full": "/photos/portraits/KLR08932-full.jpg",
    "alt": "Hiccupviews portrait — KLR08932"
  },
  {
    "src": "/photos/portraits/KLR08956-grid.jpg",
    "full": "/photos/portraits/KLR08956-full.jpg",
    "alt": "Hiccupviews portrait — KLR08956"
  },
  {
    "src": "/photos/portraits/KLR09507-grid.jpg",
    "full": "/photos/portraits/KLR09507-full.jpg",
    "alt": "Hiccupviews portrait — KLR09507"
  },
  {
    "src": "/photos/portraits/KLR09564-grid.jpg",
    "full": "/photos/portraits/KLR09564-full.jpg",
    "alt": "Hiccupviews portrait — KLR09564"
  },
  {
    "src": "/photos/portraits/KLR09951-grid.jpg",
    "full": "/photos/portraits/KLR09951-full.jpg",
    "alt": "Hiccupviews portrait — KLR09951"
  }
];

// 35 event photos (grid + full).
export const eventPhotos: AlbumPhoto[] = [
  {
    "src": "/photos/events/DSC00119-grid.jpg",
    "full": "/photos/events/DSC00119-full.jpg",
    "alt": "Hiccupviews event — DSC00119"
  },
  {
    "src": "/photos/events/DSC03575-grid.jpg",
    "full": "/photos/events/DSC03575-full.jpg",
    "alt": "Hiccupviews event — DSC03575"
  },
  {
    "src": "/photos/events/DSC03705-grid.jpg",
    "full": "/photos/events/DSC03705-full.jpg",
    "alt": "Hiccupviews event — DSC03705"
  },
  {
    "src": "/photos/events/DSC05815-2-grid.jpg",
    "full": "/photos/events/DSC05815-2-full.jpg",
    "alt": "Hiccupviews event — DSC05815-2"
  },
  {
    "src": "/photos/events/DSC05842-2-grid.jpg",
    "full": "/photos/events/DSC05842-2-full.jpg",
    "alt": "Hiccupviews event — DSC05842-2"
  },
  {
    "src": "/photos/events/DSC05889-grid.jpg",
    "full": "/photos/events/DSC05889-full.jpg",
    "alt": "Hiccupviews event — DSC05889"
  },
  {
    "src": "/photos/events/DSC05951-2-grid.jpg",
    "full": "/photos/events/DSC05951-2-full.jpg",
    "alt": "Hiccupviews event — DSC05951-2"
  },
  {
    "src": "/photos/events/DSC06051-2-grid.jpg",
    "full": "/photos/events/DSC06051-2-full.jpg",
    "alt": "Hiccupviews event — DSC06051-2"
  },
  {
    "src": "/photos/events/DSC06061-grid.jpg",
    "full": "/photos/events/DSC06061-full.jpg",
    "alt": "Hiccupviews event — DSC06061"
  },
  {
    "src": "/photos/events/DSC06248-grid.jpg",
    "full": "/photos/events/DSC06248-full.jpg",
    "alt": "Hiccupviews event — DSC06248"
  },
  {
    "src": "/photos/events/DSC09514-grid.jpg",
    "full": "/photos/events/DSC09514-full.jpg",
    "alt": "Hiccupviews event — DSC09514"
  },
  {
    "src": "/photos/events/DSC09516-grid.jpg",
    "full": "/photos/events/DSC09516-full.jpg",
    "alt": "Hiccupviews event — DSC09516"
  },
  {
    "src": "/photos/events/DSC09663-grid.jpg",
    "full": "/photos/events/DSC09663-full.jpg",
    "alt": "Hiccupviews event — DSC09663"
  },
  {
    "src": "/photos/events/KLR00175-grid.jpg",
    "full": "/photos/events/KLR00175-full.jpg",
    "alt": "Hiccupviews event — KLR00175"
  },
  {
    "src": "/photos/events/KLR01235-grid.jpg",
    "full": "/photos/events/KLR01235-full.jpg",
    "alt": "Hiccupviews event — KLR01235"
  },
  {
    "src": "/photos/events/KLR01259-grid.jpg",
    "full": "/photos/events/KLR01259-full.jpg",
    "alt": "Hiccupviews event — KLR01259"
  },
  {
    "src": "/photos/events/KLR02013-grid.jpg",
    "full": "/photos/events/KLR02013-full.jpg",
    "alt": "Hiccupviews event — KLR02013"
  },
  {
    "src": "/photos/events/KLR02129-grid.jpg",
    "full": "/photos/events/KLR02129-full.jpg",
    "alt": "Hiccupviews event — KLR02129"
  },
  {
    "src": "/photos/events/KLR02172-grid.jpg",
    "full": "/photos/events/KLR02172-full.jpg",
    "alt": "Hiccupviews event — KLR02172"
  },
  {
    "src": "/photos/events/KLR02179-grid.jpg",
    "full": "/photos/events/KLR02179-full.jpg",
    "alt": "Hiccupviews event — KLR02179"
  },
  {
    "src": "/photos/events/KLR02369-grid.jpg",
    "full": "/photos/events/KLR02369-full.jpg",
    "alt": "Hiccupviews event — KLR02369"
  },
  {
    "src": "/photos/events/KLR02385-grid.jpg",
    "full": "/photos/events/KLR02385-full.jpg",
    "alt": "Hiccupviews event — KLR02385"
  },
  {
    "src": "/photos/events/KLR02407-grid.jpg",
    "full": "/photos/events/KLR02407-full.jpg",
    "alt": "Hiccupviews event — KLR02407"
  },
  {
    "src": "/photos/events/KLR02469-grid.jpg",
    "full": "/photos/events/KLR02469-full.jpg",
    "alt": "Hiccupviews event — KLR02469"
  },
  {
    "src": "/photos/events/KLR02746-grid.jpg",
    "full": "/photos/events/KLR02746-full.jpg",
    "alt": "Hiccupviews event — KLR02746"
  },
  {
    "src": "/photos/events/KLR03647-grid.jpg",
    "full": "/photos/events/KLR03647-full.jpg",
    "alt": "Hiccupviews event — KLR03647"
  },
  {
    "src": "/photos/events/KLR03983-grid.jpg",
    "full": "/photos/events/KLR03983-full.jpg",
    "alt": "Hiccupviews event — KLR03983"
  },
  {
    "src": "/photos/events/KLR05613-grid.jpg",
    "full": "/photos/events/KLR05613-full.jpg",
    "alt": "Hiccupviews event — KLR05613"
  },
  {
    "src": "/photos/events/KLR06673-grid.jpg",
    "full": "/photos/events/KLR06673-full.jpg",
    "alt": "Hiccupviews event — KLR06673"
  },
  {
    "src": "/photos/events/KLR06776-grid.jpg",
    "full": "/photos/events/KLR06776-full.jpg",
    "alt": "Hiccupviews event — KLR06776"
  },
  {
    "src": "/photos/events/KLR06831-grid.jpg",
    "full": "/photos/events/KLR06831-full.jpg",
    "alt": "Hiccupviews event — KLR06831"
  },
  {
    "src": "/photos/events/KLR06955-grid.jpg",
    "full": "/photos/events/KLR06955-full.jpg",
    "alt": "Hiccupviews event — KLR06955"
  },
  {
    "src": "/photos/events/KLR07029-grid.jpg",
    "full": "/photos/events/KLR07029-full.jpg",
    "alt": "Hiccupviews event — KLR07029"
  },
  {
    "src": "/photos/events/KLR07189-grid.jpg",
    "full": "/photos/events/KLR07189-full.jpg",
    "alt": "Hiccupviews event — KLR07189"
  },
  {
    "src": "/photos/events/KLR07205-grid.jpg",
    "full": "/photos/events/KLR07205-full.jpg",
    "alt": "Hiccupviews event — KLR07205"
  }
];
